In [14]:
list1 = [2]*100

In [3]:
list2 = list1.copy()

In [15]:
while list1:
    list2.append(list1.pop()**2)

In [16]:
print(list2[-10:-1])

[4, 4, 4, 4, 4, 4, 4, 4, 4]


In [4]:
a = [1,2,3]
b = [4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


In [5]:
# Two lists cannot be multiplied

In [6]:
print(3 in a)

True


In [8]:
min(a)

1

In [9]:
max(a)

3

In [10]:
# tuples can be added
a = (1,2,3)
b = (4,5,6)
print(a+b)


(1, 2, 3, 4, 5, 6)


In [11]:
a = a+b

In [12]:
a

(1, 2, 3, 4, 5, 6)

In [13]:
test = """
This is a test
of multi-line strings
in Python.
"""

test2 = "This is a test of \"Viking\" in Python"

print(test)
print(test2)


This is a test
of multi-line strings
in Python.

This is a test of "Viking" in Python


In [ ]:
# \\is used inside strings to use speacial characters

In [15]:
name = "Aditya"
print(f"My name is {name}")

My name is Aditya


In [16]:
num = 25
for i in range(1,11):
    print(f"Table for {num}*{i} = {num*i}")

Table for 25*1 = 25
Table for 25*2 = 50
Table for 25*3 = 75
Table for 25*4 = 100
Table for 25*5 = 125
Table for 25*6 = 150
Table for 25*7 = 175
Table for 25*8 = 200
Table for 25*9 = 225
Table for 25*10 = 250


In [18]:
s = {x:(lambda x:x*x)(x) for x in range(1,10)}

In [19]:
s

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [20]:
# python allows variables to start with underscore
__a = 10

In [27]:
# sort a map on basis of keys
s = {1:2,3:4,5:6,7:8,9:10}
sorted(s.keys())
print(s)

{1: 2, 3: 4, 5: 6, 7: 8, 9: 10}


In [28]:
new_set = {1,2,3,4,5}

In [30]:
# interning in python
a = 10
b = 10
print(a is b)
print(id(a))
print(id(b))
# range of interning is -5 to 256

True
140717383996488
140717383996488


In [32]:
# interning is done for strings also
a = "Aditya"
b = "Aditya"
print(a is b)
print(id(a))
print(id(b))

True
2419757494128
2419757494128


In [34]:
m = {x:(lambda x:x*x)(x) for x in range(1,10)}
m

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [37]:
import sys
a = sys.intern("Aditya")
b = sys.intern("Aditya")
print(a is b)

True


In [41]:
# map to calculate freq of characters in a string in one line
s = "XYX is currently working at Wiley Edge India Pvt Ltd"
freq = {x:(lambda s,x:s.count(x))(s,x) for x in s if x!=' '}

In [43]:
# python program to check if a number is palindrome
num = 12321
temp = 0
while(num>temp):
    temp = temp*10+num%10
    num = num//10
print(num==temp or num==temp//10)

True


In [46]:
# python program to find intersection of two lists
a = [1,2,3,4,5]
b = [4,9,5,6,7,8]
a.sort()
b.sort()
i = 0
j = 0
while i<len(a) and j<len(b):
    if(a[i] == b[j]):
        print(a[i])
        i+=1
        j+=1
    elif a[i]<b[j]:
        i+=1
    else:
        j+=1

4
5


In [50]:
# find the first non-repeating character in a string
s = "AAAAAAAAAAAAAAbbbbbbbbbbbbbbbbbbcxb"
freq = {}
for i in s:
    if i in freq:
        freq[i]+=1
    else:
        freq[i]=1
for i in s:
    if freq[i]==1:
        print(i)
        break

c


In [55]:
# linspace function in numpy
# linspace(start,stop,num)
# num is the number of elements to be generated
import numpy as np
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [58]:
# using reversed function with range
for i in reversed(range(1,10)):
    print(i, end = " ")

9 8 7 6 5 4 3 2 1 

In [60]:
# difference between pass and continue
# pass is used to do nothing
# continue is used to skip the current iteration

In [69]:
# various arithmetic operations on numpy arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a+b)

print(a-b)

print(a*b)

print(a/b)

print(a%b)

print(a**b)




[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]
[      1     128    6561  262144 9765625]


In [65]:
# various unary operations on numpy arrays

a = np.array([1,2,3,4,5])

print(a.sum())

print(a.min())

print(a.max())

print(a.cumsum())

print(a.cumprod())

print(a.mean())

print(a.std())

print(a.var())

# any and all functions in numpy
# any returns true if any element is true
# all returns true if all elements are true

print(a.any())

print(a.all())

15
1
5
[ 1  3  6 10 15]
[  1   2   6  24 120]
3.0
1.4142135623730951
2.0
True
True


In [68]:
# various bitwise operations on numpy arrays

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(a&b)

print(a|b)

print(a^b)

print(~a)

# left shift and right shift
# left shift is equivalent to multiplying by 2
# right shift is equivalent to dividing by 2
# symbol is << and >>
# a<<2 means a*2^2
# a>>2 means a/2^2

print(a<<2)

print(a>>2)

[0 2 0 0 0]
[ 7  7 11 13 15]
[ 7  5 11 13 15]
[-2 -3 -4 -5 -6]
[ 4  8 12 16 20]
[0 0 0 1 1]


In [70]:
# various logical operations on numpy arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a>b)

print(a<b)

print(a==b)

print(a!=b)

print(a>=b)

print(a<=b)

[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]


In [80]:
def takeInput():
    print("Enter two lists to be merged")
    a = eval(input("Enter list1 : "))
    b = eval(input("Enter list2 : "))
    return a,b

def sortList(a):
    # bubble sort
    for i in range(len(a)):
        for j in range(len(a)-i-1):
            if a[j]>a[j+1]:
                a[j],a[j+1] = a[j+1],a[j]
    return a

def mergeList(a,b):
    a = sortList(a)
    b = sortList(b)
    c = []
    i = 0
    j = 0
    while i<len(a) and j<len(b):
        if a[i]<b[j]:
            c.append(a[i])
            i+=1
        else:
            c.append(b[j])
            j+=1
    while i<len(a):
        c.append(a[i])
        i+=1
    while j<len(b):
        c.append(b[j])
        j+=1
    return c

def findMedian(c):
    index = len(c)//2
    if len(c)%2==0:
        return (c[index]+c[index-1])/2
    return c[index]

def findMode(c):
    # python program to find mode of a list
    freq = {}
    for i in c:
        if i in freq:
            freq[i]+=1
        else:
            freq[i]=1
    max_freq = 0
    mode = 0
    for i in freq:
        if freq[i]>max_freq:
            max_freq = freq[i]
            mode = i
    return mode

def callFunctions():
    print("**************************************************")
    a,b = takeInput()
    print("**************************************************")
    c = mergeList(a,b)
    print("New sorted list is : ")
    print(c)
    print(f"Median of sorted List is : {findMedian(c)}")
    if len(c)>0:
        print(f"Mean of sorted list is : {sum(c)/len(c)}")
    print(f"Mode of sorted list is {findMode(c)}")


In [81]:
callFunctions()

Enter two lists to be merged
[1, 2, 2, 3, 4, 5, 6, 7, 9, 10]
Median of sorted List is : 4.5
Mean of sorted list is : 4.9
Mode of sorted list is 2


In [ ]:
def toDoList():
    